name: Hourly Cost Evaluation Github
on:
  schedule:
  - cron: '0 * * * *'  # This cron expression schedules the workflow to run every hour

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

  evaluate-cost:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Evaluate GitHub Actions Cost
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub-provided environment variables to get the current repository
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          # Fetch workflow run usage data
          usage=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs" | \
            jq '.workflow_runs[] | {id: .id, name: .name, run_attempt: .run_attempt, billable: .billable}')

          echo "Workflow Usage Data:"
          echo "$usage"

          # Assuming a cost of $0.008 per minute for Linux runners (standard rate)
          COST_PER_MINUTE=0.008

          # Calculate total minutes used and cost
          total_minutes=$(echo "$usage" | jq '[.billable[].total_minutes] | add // 0')
          total_cost=$(echo "$total_minutes * $COST_PER_MINUTE" | bc)

          echo "Total Minutes Used: $total_minutes"
          echo "Estimated Cost: $total_cost USD"
